#Database settings
spring:
  config:
    import: optional:file:./back/credential.yml
  main.allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.199/P6_OCR
    username: ocr
    password: openclassrooms123456
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

#JWT Security
fr.ishtamar.security.jwt:
  lifespan: 9999 #jwt duration in minutes
  secret: 1117566B59812468367639792F423E4528482B4D6253A95468574B5A71347211
  dev-url: ${server.servlet.context-path}/
  prod-url: test.com
  password-regex: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,60}$

#Server settings
server:
  port: 3001
  servlet.context-path: /api

#Logging levels
logging:
  level:
    root: ERROR
    org.springframework.boot.web.embedded.tomcat: INFO